### ISSUE TITLE
OMX_ErrorHardware on OMX_Init() failure

### ISSUE THREAD

**Issue by timcortesi** [dickontoo/omxtx#12]
I'm not sure if this is a hardware specific issue, but when I try to run omxtx, I get an error on the OMX_Init function call.  When I print the error code, I get: 0x80001009.  After looking this up, apparently it corresponds to the following:

OMX_ErrorHardware 	 The hardware failed to respond as expected

I understand that this is an OpenMAX error code, and is not specifically related to omxtx, but was hoping somebody could lend some insight into this issue.  The compliation process went fine, and I am running the latest version of the raspberry pi firmware ala rpi-udate.  I do have my CPU overclocked to 900mhz (from 700mhz), but have not experienced any other issues.  

I apologize if this is the wrong place to post this issue, but could not find a better location. If there is a more correct place, please let me know.

**Comment by R4P70R** [comment]
I know it's late for this reply but for futur researches:
Don't forget to call the function "bcm_host_init();" before using OMX_Init 

"The Raspberry Pi requires that the bcm_host_init() function is called first before any GPU calls can be made." - http://elinux.org/Raspberry_Pi_VideoCore_APIs

**Comment by dickontoo** [comment]
Not really a problem in this case, though.  The code is correct, and it's a misconfiguration on the Pi in question which caused this issue to be opened.  I'm going to close it now.

Thanks.
