### ISSUE TITLE
input output not doing anything ?

### ISSUE THREAD

**Issue by syst5** [dickontoo/omxtx#18]
I'm trying omtx for the 1st time to transcode a live video from one rtmp input to another rtmp output, both file name terminated with .flv and nothing happening. Tried a local file name output and nothing happening also. Input does connect successfully to the nginx server but as i said nothing on the other end neither as a file.

Input:
Input #0, flv, from 'rtmp://127.0.0.1/live/video.flv':
  Metadata:
    title           : livestream
    encoder         : Lavf57.66.100
  Duration: 00:00:00.00, start: 1278.914000, bitrate: N/A
    Stream #0.0: Video: h264 (Constrained Baseline), yuvj420p, 1920x1080, 30 fps, 1k tbn

Output:
Output #0, flv, to 'video.flv':
    Stream #0.0: Video: libx264, 1280x720, q=-1--1, 1500 kb/s, 30 fps

**Comment by dickontoo** [comment]
There's no support for anything other than basic file output -- .mp4 mostly -- as I didn't think it was worth it.  Feel free to add it and submit patches...
